// Copyright Quesma, licensed under the Elastic License 2.0.
// SPDX-License-Identifier: Elastic-2.0

package dialect_sqlparse

import "lexer/core"

// Based on https://github.com/andialbrecht/sqlparse/blob/38c065b86ac43f76ffd319747e57096ed78bfa63/sqlparse/keywords.py

var KeywordToken = core.TokenType{
	Name:        "tokens.Keyword",
	Description: "General keyword token",
}

var DMLKeywordToken = core.TokenType{
	Name:        "tokens.Keyword.DML",
	Description: "DML keyword token (e.g. SELECT, INSERT, UPDATE, DELETE)",
}

var DDLKeywordToken = core.TokenType{
	Name:        "tokens.Keyword.DDL",
	Description: "DDL keyword token (e.g. DROP, CREATE, ALTER)",
}

var DCLKeywordToken = core.TokenType{
	Name:        "tokens.Keyword.DCL",
	Description: "DCL keyword token (e.g. GRANT, REVOKE)",
}

var CTEKeywordToken = core.TokenType{
	Name:        "tokens.Keyword.CTE",
	Description: "CTE keyword token (e.g. WITH)",
}

var OrderKeywordToken = core.TokenType{
	Name:        "tokens.Keyword.Order",
	Description: "Order keyword token (e.g. ASC, DESC)",
}

var TZCastKeywordToken = core.TokenType{
	Name:        "tokens.Keyword.TZCast",
	Description: "Timezone cast keyword token (e.g. AT TIME ZONE)",
}

var OperatorToken = core.TokenType{
	Name:        "tokens.Operator",
	Description: "Operator token (e.g. DIV)",
}

var ComparisonOperatorToken = core.TokenType{
	Name:        "tokens.Operator.Comparison",
	Description: "Comparison operator token (e.g. =, <, >)",
}

var NameToken = core.TokenType{
	Name:        "tokens.Name",
	Description: "Name token",
}

var BuiltinNameToken = core.TokenType{
	Name:        "tokens.Name.Builtin",
	Description: "Builtin token (e.g. ARRAY, BIGINT, BINARY)",
}

var PlaceholderNameToken = core.TokenType{
	Name:        "tokens.Name.Placeholder",
	Description: "Placeholder token",
}

var SingleCommentToken = core.TokenType{
	Name:        "tokens.Comment.Single",
	Description: "Single-line comment token",
}

var MultilineCommentToken = core.TokenType{
	Name:        "tokens.Comment.Multiline",
	Description: "Multiline comment token",
}

var SingleHintToken = core.TokenType{
	Name:        "tokens.Comment.Single.Hint",
	Description: "Single-line hint token",
}

var MultilineHintToken = core.TokenType{
	Name:        "tokens.Comment.Multiline.Hint",
	Description: "Multiline hint token",
}

var NewlineToken = core.TokenType{
	Name:        "tokens.Newline",
	Description: "Newline token",
}

var WhitespaceToken = core.TokenType{
	Name:        "tokens.Whitespace",
	Description: "Whitespace token",
}

var AssignmentToken = core.TokenType{
	Name:        "tokens.Assignment",
	Description: "Assignment token",
}

var PunctuationToken = core.TokenType{
	Name:        "tokens.Punctuation",
	Description: "Punctuation token (e.g. ;, :, ::, (, ), )",
}

var WildcardToken = core.TokenType{
	Name:        "tokens.Wildcard",
	Description: "Wildcard token (* character)",
}

var LiteralToken = core.TokenType{
	Name:        "tokens.Literal",
	Description: "Literal token",
}

var CommandToken = core.TokenType{
	Name:        "tokens.Command",
	Description: "Command token",
}

var IntegerNumberToken = core.TokenType{
	Name:        "tokens.Number.Integer",
	Description: "Integer number token",
}

var HexadecimalNumberToken = core.TokenType{
	Name:        "tokens.Number.Hexadecimal",
	Description: "Hexadecimal number token",
}

var FloatNumberToken = core.TokenType{
	Name:        "tokens.Number.Float",
	Description: "Float number token",
}

var SingleStringToken = core.TokenType{
	Name:        "tokens.String.Single",
	Description: "Single-quoted string token",
}

var SymbolStringToken = core.TokenType{
	Name:        "tokens.String.Symbol",
	Description: "Symbol string token",
}

var SQL_REGEX = []core.Rule{
	core.NewRegexRule(`(--|# )\+.*?(\r\n|\r|\n|$)`, &SingleHintToken),
	core.NewRegexRule(`/\*\+[\s\S]*?\*/`, &MultilineHintToken),

	core.NewRegexRule(`(--|# ).*?(\r\n|\r|\n|$)`, &SingleCommentToken),
	core.NewRegexRule(`/\*[\s\S]*?\*/`, &MultilineCommentToken),

	core.NewRegexRule(`(\r\n|\r|\n)`, &NewlineToken),
	core.NewRegexRule(`\s+?`, &WhitespaceToken),

	core.NewRegexRule(`:=`, &AssignmentToken),
	core.NewRegexRule(`::`, &PunctuationToken),

	core.NewRegexRule(`\*`, &WildcardToken),

	core.NewRegexRule("`(``|[^`])*`", &NameToken),
	core.NewRegexRule(`´(´´|[^´])*´`, &NameToken),
	// TODO: doesn't compile in golang
	// core.NewRegexRule(`((?<![\w\"\$])\$(?:[_A-ZÀ-Ü]\w*)?\$)[\s\S]*?\1`, &LiteralToken),

	core.NewRegexRule(`\?`, &PlaceholderNameToken),
	core.NewRegexRule(`%(\(\w+\))?s`, &PlaceholderNameToken),

	// TODO: doesn't compile in golang
	//core.NewRegexRule(`(?<!\w)[$:?]\w+`, &PlaceholderNameToken),

	core.NewRegexRule(`\\\w+`, &CommandToken),

	// FIXME(andi): VALUES shouldn't be listed here
	// see https://github.com/andialbrecht/sqlparse/pull/64
	// AS and IN are special, it may be followed by a parenthesis, but
	// are never functions, see issue183 and issue507
	core.NewRegexRule(`(CASE|IN|VALUES|USING|FROM|AS)\b`, &KeywordToken),

	core.NewRegexRule(`(@|##|#)[A-ZÀ-Ü]\w+`, &NameToken),

	// see issue #39
	// Spaces around period `schema . name` are valid identifier
	// TODO: Spaces before period not implemented
	// TODO: doesn't compile in golang
	// core.NewRegexRule(`[A-ZÀ-Ü]\w*(?=\s*\.)`, &NameToken), // 'Name'.
	// FIXME(atronah): never match,
	// because `re.match` doesn't work with look-behind regexp feature
	// TODO: doesn't compile in golang
	//core.NewRegexRule(`(?<=\.)[A-ZÀ-Ü]\w*`, &NameToken), // .'Name'
	// TODO: doesn't compile in golang
	//core.NewRegexRule(`[A-ZÀ-Ü]\w*(?=\()`, &NameToken), // side effect: change kw to func
	core.NewRegexRule(`-?0x[\dA-F]+`, &HexadecimalNumberToken),
	core.NewRegexRule(`-?\d+(\.\d+)?E-?\d+`, &FloatNumberToken),
	// TODO: doesn't compile in golang
	//core.NewRegexRule(`(?![_A-ZÀ-Ü])-?(\d+(\.\d*)|\.\d+)(?![_A-ZÀ-Ü])`, &FloatNumberToken),
	// TODO: doesn't compile in golang
	//core.NewRegexRule(`(?![_A-ZÀ-Ü])-?\d+(?![_A-ZÀ-Ü])`, &IntegerNumberToken),
	core.NewRegexRule(`'(''|\\'|[^'])*'`, &SingleStringToken),
	// not a real string literal in ANSI SQL:
	core.NewRegexRule(`"(""|\\"|[^"])*"`, &SymbolStringToken),
	core.NewRegexRule(`(""|".*?[^\\]")`, &SymbolStringToken),
	// sqlite names can be escaped with [square brackets]. left bracket
	// cannot be preceded by word character or a right bracket --
	// otherwise it's probably an array index
	// TODO: doesn't compile in golang
	//core.NewRegexRule(`(?<![\w\])])(\[[^\]\[]+\])`, &NameToken),
	core.NewRegexRule(`((LEFT\s+|RIGHT\s+|FULL\s+)?(INNER\s+|OUTER\s+|STRAIGHT\s+)?`+
		`|(CROSS\s+|NATURAL\s+)?)?JOIN\b`, &KeywordToken),
	core.NewRegexRule(`END(\s+IF|\s+LOOP|\s+WHILE)?\b`, &KeywordToken),
	core.NewRegexRule(`NOT\s+NULL\b`, &KeywordToken),
	core.NewRegexRule(`(ASC|DESC)(\s+NULLS\s+(FIRST|LAST))?\b`, &OrderKeywordToken),
	core.NewRegexRule(`(ASC|DESC)\b`, &OrderKeywordToken),
	core.NewRegexRule(`NULLS\s+(FIRST|LAST)\b`, &OrderKeywordToken),
	core.NewRegexRule(`UNION\s+ALL\b`, &KeywordToken),
	core.NewRegexRule(`CREATE(\s+OR\s+REPLACE)?\b`, &DDLKeywordToken),
	core.NewRegexRule(`DOUBLE\s+PRECISION\b`, &BuiltinNameToken),
	core.NewRegexRule(`GROUP\s+BY\b`, &KeywordToken),
	core.NewRegexRule(`ORDER\s+BY\b`, &KeywordToken),
	core.NewRegexRule(`PRIMARY\s+KEY\b`, &KeywordToken),
	core.NewRegexRule(`HANDLER\s+FOR\b`, &KeywordToken),
	core.NewRegexRule(`GO(\s\d+)\b`, &KeywordToken),
	core.NewRegexRule(`(LATERAL\s+VIEW\s+)`+
		`(EXPLODE|INLINE|PARSE_URL_TUPLE|POSEXPLODE|STACK)\b`, &KeywordToken),
	core.NewRegexRule(`(AT|WITH')\s+TIME\s+ZONE\s+'[^']+'`, &TZCastKeywordToken),
	core.NewRegexRule(`(NOT\s+)?(LIKE|ILIKE|RLIKE)\b`, &ComparisonOperatorToken),
	core.NewRegexRule(`(NOT\s+)?(REGEXP)\b`, &ComparisonOperatorToken),
	// Check for keywords, also returns tokens.Name if regex matches
	// but the match isn't a keyword.
	//TODO: implement this core.NewRegexRule(`\w[$#\w]*`, PROCESS_AS_KEYWORD},
	core.NewRegexRule(`[;:()\[\],\.]`, &PunctuationToken),
	// JSON operators
	core.NewRegexRule(`(\->>?|#>>?|@>|<@|\?\|?|\?&|\-|#\-)`, &OperatorToken),
	core.NewRegexRule(`[<>=~!]+`, &ComparisonOperatorToken),
	core.NewRegexRule(`[+/@#%^&|^-]+`, &OperatorToken),
}

var KEYWORDS = map[string]*core.TokenType{
	"ABORT":          &KeywordToken,
	"ABS":            &KeywordToken,
	"ABSOLUTE":       &KeywordToken,
	"ACCESS":         &KeywordToken,
	"ADA":            &KeywordToken,
	"ADD":            &KeywordToken,
	"ADMIN":          &KeywordToken,
	"AFTER":          &KeywordToken,
	"AGGREGATE":      &KeywordToken,
	"ALIAS":          &KeywordToken,
	"ALL":            &KeywordToken,
	"ALLOCATE":       &KeywordToken,
	"ANALYSE":        &KeywordToken,
	"ANALYZE":        &KeywordToken,
	"ANY":            &KeywordToken,
	"ARRAYLEN":       &KeywordToken,
	"ARE":            &KeywordToken,
	"ASENSITIVE":     &KeywordToken,
	"ASSERTION":      &KeywordToken,
	"ASSIGNMENT":     &KeywordToken,
	"ASYMMETRIC":     &KeywordToken,
	"AT":             &KeywordToken,
	"ATOMIC":         &KeywordToken,
	"AUDIT":          &KeywordToken,
	"AUTHORIZATION":  &KeywordToken,
	"AUTO_INCREMENT": &KeywordToken,
	"AVG":            &KeywordToken,

	"BACKWARD":   &KeywordToken,
	"BEFORE":     &KeywordToken,
	"BEGIN":      &KeywordToken,
	"BETWEEN":    &KeywordToken,
	"BITVAR":     &KeywordToken,
	"BIT_LENGTH": &KeywordToken,
	"BOTH":       &KeywordToken,
	"BREADTH":    &KeywordToken,

	// "C":&KeywordToken,  // most likely this is an alias
	"CACHE":                 &KeywordToken,
	"CALL":                  &KeywordToken,
	"CALLED":                &KeywordToken,
	"CARDINALITY":           &KeywordToken,
	"CASCADE":               &KeywordToken,
	"CASCADED":              &KeywordToken,
	"CAST":                  &KeywordToken,
	"CATALOG":               &KeywordToken,
	"CATALOG_NAME":          &KeywordToken,
	"CHAIN":                 &KeywordToken,
	"CHARACTERISTICS":       &KeywordToken,
	"CHARACTER_LENGTH":      &KeywordToken,
	"CHARACTER_SET_CATALOG": &KeywordToken,
	"CHARACTER_SET_NAME":    &KeywordToken,
	"CHARACTER_SET_SCHEMA":  &KeywordToken,
	"CHAR_LENGTH":           &KeywordToken,
	"CHARSET":               &KeywordToken,
	"CHECK":                 &KeywordToken,
	"CHECKED":               &KeywordToken,
	"CHECKPOINT":            &KeywordToken,
	"CLASS":                 &KeywordToken,
	"CLASS_ORIGIN":          &KeywordToken,
	"CLOB":                  &KeywordToken,
	"CLOSE":                 &KeywordToken,
	"CLUSTER":               &KeywordToken,
	"COALESCE":              &KeywordToken,
	"COBOL":                 &KeywordToken,
	"COLLATE":               &KeywordToken,
	"COLLATION":             &KeywordToken,
	"COLLATION_CATALOG":     &KeywordToken,
	"COLLATION_NAME":        &KeywordToken,
	"COLLATION_SCHEMA":      &KeywordToken,
	"COLLECT":               &KeywordToken,
	"COLUMN":                &KeywordToken,
	"COLUMN_NAME":           &KeywordToken,
	"COMPRESS":              &KeywordToken,
	"COMMAND_FUNCTION":      &KeywordToken,
	"COMMAND_FUNCTION_CODE": &KeywordToken,
	"COMMENT":               &KeywordToken,
	"COMMIT":                &DMLKeywordToken,
	"COMMITTED":             &KeywordToken,
	"COMPLETION":            &KeywordToken,
	"CONCURRENTLY":          &KeywordToken,
	"CONDITION_NUMBER":      &KeywordToken,
	"CONNECT":               &KeywordToken,
	"CONNECTION":            &KeywordToken,
	"CONNECTION_NAME":       &KeywordToken,
	"CONSTRAINT":            &KeywordToken,
	"CONSTRAINTS":           &KeywordToken,
	"CONSTRAINT_CATALOG":    &KeywordToken,
	"CONSTRAINT_NAME":       &KeywordToken,
	"CONSTRAINT_SCHEMA":     &KeywordToken,
	"CONSTRUCTOR":           &KeywordToken,
	"CONTAINS":              &KeywordToken,
	"CONTINUE":              &KeywordToken,
	"CONVERSION":            &KeywordToken,
	"CONVERT":               &KeywordToken,
	"COPY":                  &KeywordToken,
	"CORRESPONDING":         &KeywordToken,
	"COUNT":                 &KeywordToken,
	"CREATEDB":              &KeywordToken,
	"CREATEUSER":            &KeywordToken,
	"CROSS":                 &KeywordToken,
	"CUBE":                  &KeywordToken,
	"CURRENT":               &KeywordToken,
	"CURRENT_DATE":          &KeywordToken,
	"CURRENT_PATH":          &KeywordToken,
	"CURRENT_ROLE":          &KeywordToken,
	"CURRENT_TIME":          &KeywordToken,
	"CURRENT_TIMESTAMP":     &KeywordToken,
	"CURRENT_USER":          &KeywordToken,
	"CURSOR":                &KeywordToken,
	"CURSOR_NAME":           &KeywordToken,
	"CYCLE":                 &KeywordToken,

	"DATA":                        &KeywordToken,
	"DATABASE":                    &KeywordToken,
	"DATETIME_INTERVAL_CODE":      &KeywordToken,
	"DATETIME_INTERVAL_PRECISION": &KeywordToken,
	"DAY":                         &KeywordToken,
	"DEALLOCATE":                  &KeywordToken,
	"DECLARE":                     &KeywordToken,
	"DEFAULT":                     &KeywordToken,
	"DEFAULTS":                    &KeywordToken,
	"DEFERRABLE":                  &KeywordToken,
	"DEFERRED":                    &KeywordToken,
	"DEFINED":                     &KeywordToken,
	"DEFINER":                     &KeywordToken,
	"DELIMITER":                   &KeywordToken,
	"DELIMITERS":                  &KeywordToken,
	"DEREF":                       &KeywordToken,
	"DESCRIBE":                    &KeywordToken,
	"DESCRIPTOR":                  &KeywordToken,
	"DESTROY":                     &KeywordToken,
	"DESTRUCTOR":                  &KeywordToken,
	"DETERMINISTIC":               &KeywordToken,
	"DIAGNOSTICS":                 &KeywordToken,
	"DICTIONARY":                  &KeywordToken,
	"DISABLE":                     &KeywordToken,
	"DISCONNECT":                  &KeywordToken,
	"DISPATCH":                    &KeywordToken,
	"DIV":                         &OperatorToken,
	"DO":                          &KeywordToken,
	"DOMAIN":                      &KeywordToken,
	"DYNAMIC":                     &KeywordToken,
	"DYNAMIC_FUNCTION":            &KeywordToken,
	"DYNAMIC_FUNCTION_CODE":       &KeywordToken,

	"EACH":      &KeywordToken,
	"ENABLE":    &KeywordToken,
	"ENCODING":  &KeywordToken,
	"ENCRYPTED": &KeywordToken,
	"END-EXEC":  &KeywordToken,
	"ENGINE":    &KeywordToken,
	"EQUALS":    &KeywordToken,
	"ESCAPE":    &KeywordToken,
	"EVERY":     &KeywordToken,
	"EXCEPT":    &KeywordToken,
	"EXCEPTION": &KeywordToken,
	"EXCLUDING": &KeywordToken,
	"EXCLUSIVE": &KeywordToken,
	"EXEC":      &KeywordToken,
	"EXECUTE":   &KeywordToken,
	"EXISTING":  &KeywordToken,
	"EXISTS":    &KeywordToken,
	"EXPLAIN":   &KeywordToken,
	"EXTERNAL":  &KeywordToken,
	"EXTRACT":   &KeywordToken,

	"FALSE":    &KeywordToken,
	"FETCH":    &KeywordToken,
	"FILE":     &KeywordToken,
	"FINAL":    &KeywordToken,
	"FIRST":    &KeywordToken,
	"FORCE":    &KeywordToken,
	"FOREACH":  &KeywordToken,
	"FOREIGN":  &KeywordToken,
	"FORTRAN":  &KeywordToken,
	"FORWARD":  &KeywordToken,
	"FOUND":    &KeywordToken,
	"FREE":     &KeywordToken,
	"FREEZE":   &KeywordToken,
	"FULL":     &KeywordToken,
	"FUNCTION": &KeywordToken,

	// "G":&KeywordToken,
	"GENERAL":   &KeywordToken,
	"GENERATED": &KeywordToken,
	"GET":       &KeywordToken,
	"GLOBAL":    &KeywordToken,
	"GO":        &KeywordToken,
	"GOTO":      &KeywordToken,
	"GRANTED":   &KeywordToken,
	"GROUPING":  &KeywordToken,

	"HAVING":    &KeywordToken,
	"HIERARCHY": &KeywordToken,
	"HOLD":      &KeywordToken,
	"HOUR":      &KeywordToken,
	"HOST":      &KeywordToken,

	"IDENTIFIED": &KeywordToken,
	"IDENTITY":   &KeywordToken,
	"IGNORE":     &KeywordToken,
	"ILIKE":      &KeywordToken,
	"IMMEDIATE":  &KeywordToken,
	"IMMUTABLE":  &KeywordToken,

	"IMPLEMENTATION": &KeywordToken,
	"IMPLICIT":       &KeywordToken,
	"INCLUDING":      &KeywordToken,
	"INCREMENT":      &KeywordToken,
	"INDEX":          &KeywordToken,

	"INDICATOR":    &KeywordToken,
	"INFIX":        &KeywordToken,
	"INHERITS":     &KeywordToken,
	"INITIAL":      &KeywordToken,
	"INITIALIZE":   &KeywordToken,
	"INITIALLY":    &KeywordToken,
	"INOUT":        &KeywordToken,
	"INPUT":        &KeywordToken,
	"INSENSITIVE":  &KeywordToken,
	"INSTANTIABLE": &KeywordToken,
	"INSTEAD":      &KeywordToken,
	"INTERSECT":    &KeywordToken,
	"INTO":         &KeywordToken,
	"INVOKER":      &KeywordToken,
	"IS":           &KeywordToken,
	"ISNULL":       &KeywordToken,
	"ISOLATION":    &KeywordToken,
	"ITERATE":      &KeywordToken,

	// "K":&KeywordToken,
	"KEY":        &KeywordToken,
	"KEY_MEMBER": &KeywordToken,
	"KEY_TYPE":   &KeywordToken,

	"LANCOMPILER":    &KeywordToken,
	"LANGUAGE":       &KeywordToken,
	"LARGE":          &KeywordToken,
	"LAST":           &KeywordToken,
	"LATERAL":        &KeywordToken,
	"LEADING":        &KeywordToken,
	"LENGTH":         &KeywordToken,
	"LESS":           &KeywordToken,
	"LEVEL":          &KeywordToken,
	"LIMIT":          &KeywordToken,
	"LISTEN":         &KeywordToken,
	"LOAD":           &KeywordToken,
	"LOCAL":          &KeywordToken,
	"LOCALTIME":      &KeywordToken,
	"LOCALTIMESTAMP": &KeywordToken,
	"LOCATION":       &KeywordToken,
	"LOCATOR":        &KeywordToken,
	"LOCK":           &KeywordToken,
	"LOWER":          &KeywordToken,

	// "M":&KeywordToken,
	"MAP":                  &KeywordToken,
	"MATCH":                &KeywordToken,
	"MAXEXTENTS":           &KeywordToken,
	"MAXVALUE":             &KeywordToken,
	"MESSAGE_LENGTH":       &KeywordToken,
	"MESSAGE_OCTET_LENGTH": &KeywordToken,
	"MESSAGE_TEXT":         &KeywordToken,
	"METHOD":               &KeywordToken,
	"MINUTE":               &KeywordToken,
	"MINUS":                &KeywordToken,
	"MINVALUE":             &KeywordToken,
	"MOD":                  &KeywordToken,
	"MODE":                 &KeywordToken,
	"MODIFIES":             &KeywordToken,
	"MODIFY":               &KeywordToken,
	"MONTH":                &KeywordToken,
	"MORE":                 &KeywordToken,
	"MOVE":                 &KeywordToken,
	"MUMPS":                &KeywordToken,

	"NAMES":        &KeywordToken,
	"NATIONAL":     &KeywordToken,
	"NATURAL":      &KeywordToken,
	"NCHAR":        &KeywordToken,
	"NCLOB":        &KeywordToken,
	"NEW":          &KeywordToken,
	"NEXT":         &KeywordToken,
	"NO":           &KeywordToken,
	"NOAUDIT":      &KeywordToken,
	"NOCOMPRESS":   &KeywordToken,
	"NOCREATEDB":   &KeywordToken,
	"NOCREATEUSER": &KeywordToken,
	"NONE":         &KeywordToken,
	"NOT":          &KeywordToken,
	"NOTFOUND":     &KeywordToken,
	"NOTHING":      &KeywordToken,
	"NOTIFY":       &KeywordToken,
	"NOTNULL":      &KeywordToken,
	"NOWAIT":       &KeywordToken,
	"NULL":         &KeywordToken,
	"NULLABLE":     &KeywordToken,
	"NULLIF":       &KeywordToken,

	"OBJECT":       &KeywordToken,
	"OCTET_LENGTH": &KeywordToken,
	"OF":           &KeywordToken,
	"OFF":          &KeywordToken,
	"OFFLINE":      &KeywordToken,
	"OFFSET":       &KeywordToken,
	"OIDS":         &KeywordToken,
	"OLD":          &KeywordToken,
	"ONLINE":       &KeywordToken,
	"ONLY":         &KeywordToken,
	"OPEN":         &KeywordToken,
	"OPERATION":    &KeywordToken,
	"OPERATOR":     &KeywordToken,
	"OPTION":       &KeywordToken,
	"OPTIONS":      &KeywordToken,
	"ORDINALITY":   &KeywordToken,
	"OUT":          &KeywordToken,
	"OUTPUT":       &KeywordToken,
	"OVERLAPS":     &KeywordToken,
	"OVERLAY":      &KeywordToken,
	"OVERRIDING":   &KeywordToken,
	"OWNER":        &KeywordToken,

	"QUARTER": &KeywordToken,

	"PAD":                        &KeywordToken,
	"PARAMETER":                  &KeywordToken,
	"PARAMETERS":                 &KeywordToken,
	"PARAMETER_MODE":             &KeywordToken,
	"PARAMETER_NAME":             &KeywordToken,
	"PARAMETER_ORDINAL_POSITION": &KeywordToken,
	"PARAMETER_SPECIFIC_CATALOG": &KeywordToken,
	"PARAMETER_SPECIFIC_NAME":    &KeywordToken,
	"PARAMETER_SPECIFIC_SCHEMA":  &KeywordToken,
	"PARTIAL":                    &KeywordToken,
	"PASCAL":                     &KeywordToken,
	"PCTFREE":                    &KeywordToken,
	"PENDANT":                    &KeywordToken,
	"PLACING":                    &KeywordToken,
	"PLI":                        &KeywordToken,
	"POSITION":                   &KeywordToken,
	"POSTFIX":                    &KeywordToken,
	"PRECISION":                  &KeywordToken,
	"PREFIX":                     &KeywordToken,
	"PREORDER":                   &KeywordToken,
	"PREPARE":                    &KeywordToken,
	"PRESERVE":                   &KeywordToken,
	"PRIMARY":                    &KeywordToken,
	"PRIOR":                      &KeywordToken,
	"PRIVILEGES":                 &KeywordToken,
	"PROCEDURAL":                 &KeywordToken,
	"PROCEDURE":                  &KeywordToken,
	"PUBLIC":                     &KeywordToken,

	"RAISE":                 &KeywordToken,
	"RAW":                   &KeywordToken,
	"READ":                  &KeywordToken,
	"READS":                 &KeywordToken,
	"RECHECK":               &KeywordToken,
	"RECURSIVE":             &KeywordToken,
	"REF":                   &KeywordToken,
	"REFERENCES":            &KeywordToken,
	"REFERENCING":           &KeywordToken,
	"REINDEX":               &KeywordToken,
	"RELATIVE":              &KeywordToken,
	"RENAME":                &KeywordToken,
	"REPEATABLE":            &KeywordToken,
	"RESET":                 &KeywordToken,
	"RESOURCE":              &KeywordToken,
	"RESTART":               &KeywordToken,
	"RESTRICT":              &KeywordToken,
	"RESULT":                &KeywordToken,
	"RETURN":                &KeywordToken,
	"RETURNED_LENGTH":       &KeywordToken,
	"RETURNED_OCTET_LENGTH": &KeywordToken,
	"RETURNED_SQLSTATE":     &KeywordToken,
	"RETURNING":             &KeywordToken,
	"RETURNS":               &KeywordToken,
	"RIGHT":                 &KeywordToken,
	"ROLE":                  &KeywordToken,
	"ROLLBACK":              &DMLKeywordToken,
	"ROLLUP":                &KeywordToken,
	"ROUTINE":               &KeywordToken,
	"ROUTINE_CATALOG":       &KeywordToken,
	"ROUTINE_NAME":          &KeywordToken,
	"ROUTINE_SCHEMA":        &KeywordToken,
	"ROWS":                  &KeywordToken,
	"ROW_COUNT":             &KeywordToken,
	"RULE":                  &KeywordToken,

	"SAVE_POINT":    &KeywordToken,
	"SCALE":         &KeywordToken,
	"SCHEMA":        &KeywordToken,
	"SCHEMA_NAME":   &KeywordToken,
	"SCOPE":         &KeywordToken,
	"SCROLL":        &KeywordToken,
	"SEARCH":        &KeywordToken,
	"SECOND":        &KeywordToken,
	"SECURITY":      &KeywordToken,
	"SELF":          &KeywordToken,
	"SENSITIVE":     &KeywordToken,
	"SEQUENCE":      &KeywordToken,
	"SERIALIZABLE":  &KeywordToken,
	"SERVER_NAME":   &KeywordToken,
	"SESSION":       &KeywordToken,
	"SESSION_USER":  &KeywordToken,
	"SETOF":         &KeywordToken,
	"SETS":          &KeywordToken,
	"SHARE":         &KeywordToken,
	"SHOW":          &KeywordToken,
	"SIMILAR":       &KeywordToken,
	"SIMPLE":        &KeywordToken,
	"SIZE":          &KeywordToken,
	"SOME":          &KeywordToken,
	"SOURCE":        &KeywordToken,
	"SPACE":         &KeywordToken,
	"SPECIFIC":      &KeywordToken,
	"SPECIFICTYPE":  &KeywordToken,
	"SPECIFIC_NAME": &KeywordToken,
	"SQL":           &KeywordToken,
	"SQLBUF":        &KeywordToken,
	"SQLCODE":       &KeywordToken,
	"SQLERROR":      &KeywordToken,
	"SQLEXCEPTION":  &KeywordToken,
	"SQLSTATE":      &KeywordToken,
	"SQLWARNING":    &KeywordToken,
	"STABLE":        &KeywordToken,
	"START":         &DMLKeywordToken,
	// "STATE":&KeywordToken,
	"STATEMENT":       &KeywordToken,
	"STATIC":          &KeywordToken,
	"STATISTICS":      &KeywordToken,
	"STDIN":           &KeywordToken,
	"STDOUT":          &KeywordToken,
	"STORAGE":         &KeywordToken,
	"STRICT":          &KeywordToken,
	"STRUCTURE":       &KeywordToken,
	"STYPE":           &KeywordToken,
	"SUBCLASS_ORIGIN": &KeywordToken,
	"SUBLIST":         &KeywordToken,
	"SUBSTRING":       &KeywordToken,
	"SUCCESSFUL":      &KeywordToken,
	"SUM":             &KeywordToken,
	"SYMMETRIC":       &KeywordToken,
	"SYNONYM":         &KeywordToken,
	"SYSID":           &KeywordToken,
	"SYSTEM":          &KeywordToken,
	"SYSTEM_USER":     &KeywordToken,

	"TABLE":                    &KeywordToken,
	"TABLE_NAME":               &KeywordToken,
	"TEMP":                     &KeywordToken,
	"TEMPLATE":                 &KeywordToken,
	"TEMPORARY":                &KeywordToken,
	"TERMINATE":                &KeywordToken,
	"THAN":                     &KeywordToken,
	"TIMESTAMP":                &KeywordToken,
	"TIMEZONE_HOUR":            &KeywordToken,
	"TIMEZONE_MINUTE":          &KeywordToken,
	"TO":                       &KeywordToken,
	"TOAST":                    &KeywordToken,
	"TRAILING":                 &KeywordToken,
	"TRANSATION":               &KeywordToken,
	"TRANSACTIONS_COMMITTED":   &KeywordToken,
	"TRANSACTIONS_ROLLED_BACK": &KeywordToken,
	"TRANSATION_ACTIVE":        &KeywordToken,
	"TRANSFORM":                &KeywordToken,
	"TRANSFORMS":               &KeywordToken,
	"TRANSLATE":                &KeywordToken,
	"TRANSLATION":              &KeywordToken,
	"TREAT":                    &KeywordToken,
	"TRIGGER":                  &KeywordToken,
	"TRIGGER_CATALOG":          &KeywordToken,
	"TRIGGER_NAME":             &KeywordToken,
	"TRIGGER_SCHEMA":           &KeywordToken,
	"TRIM":                     &KeywordToken,
	"TRUE":                     &KeywordToken,
	"TRUSTED":                  &KeywordToken,
	"TYPE":                     &KeywordToken,

	"UID":                       &KeywordToken,
	"UNCOMMITTED":               &KeywordToken,
	"UNDER":                     &KeywordToken,
	"UNENCRYPTED":               &KeywordToken,
	"UNION":                     &KeywordToken,
	"UNIQUE":                    &KeywordToken,
	"UNKNOWN":                   &KeywordToken,
	"UNLISTEN":                  &KeywordToken,
	"UNNAMED":                   &KeywordToken,
	"UNNEST":                    &KeywordToken,
	"UNTIL":                     &KeywordToken,
	"UPPER":                     &KeywordToken,
	"USAGE":                     &KeywordToken,
	"USE":                       &KeywordToken,
	"USER":                      &KeywordToken,
	"USER_DEFINED_TYPE_CATALOG": &KeywordToken,
	"USER_DEFINED_TYPE_NAME":    &KeywordToken,
	"USER_DEFINED_TYPE_SCHEMA":  &KeywordToken,
	"USING":                     &KeywordToken,

	"VACUUM":    &KeywordToken,
	"VALID":     &KeywordToken,
	"VALIDATE":  &KeywordToken,
	"VALIDATOR": &KeywordToken,
	"VALUES":    &KeywordToken,
	"VARIABLE":  &KeywordToken,
	"VERBOSE":   &KeywordToken,
	"VERSION":   &KeywordToken,
	"VIEW":      &KeywordToken,
	"VOLATILE":  &KeywordToken,

	"WEEK":     &KeywordToken,
	"WHENEVER": &KeywordToken,
	"WITH":     &CTEKeywordToken,
	"WITHOUT":  &KeywordToken,
	"WORK":     &KeywordToken,
	"WRITE":    &KeywordToken,

	"YEAR": &KeywordToken,

	"ZONE": &KeywordToken,

	// Name.Builtin
	"ARRAY":          &BuiltinNameToken,
	"BIGINT":         &BuiltinNameToken,
	"BINARY":         &BuiltinNameToken,
	"BIT":            &BuiltinNameToken,
	"BLOB":           &BuiltinNameToken,
	"BOOLEAN":        &BuiltinNameToken,
	"CHAR":           &BuiltinNameToken,
	"CHARACTER":      &BuiltinNameToken,
	"DATE":           &BuiltinNameToken,
	"DEC":            &BuiltinNameToken,
	"DECIMAL":        &BuiltinNameToken,
	"FILE_TYPE":      &BuiltinNameToken,
	"FLOAT":          &BuiltinNameToken,
	"INT":            &BuiltinNameToken,
	"INT8":           &BuiltinNameToken,
	"INTEGER":        &BuiltinNameToken,
	"INTERVAL":       &BuiltinNameToken,
	"LONG":           &BuiltinNameToken,
	"NATURALN":       &BuiltinNameToken,
	"NVARCHAR":       &BuiltinNameToken,
	"NUMBER":         &BuiltinNameToken,
	"NUMERIC":        &BuiltinNameToken,
	"PLS_INTEGER":    &BuiltinNameToken,
	"POSITIVE":       &BuiltinNameToken,
	"POSITIVEN":      &BuiltinNameToken,
	"REAL":           &BuiltinNameToken,
	"ROWID":          &BuiltinNameToken,
	"ROWLABEL":       &BuiltinNameToken,
	"ROWNUM":         &BuiltinNameToken,
	"SERIAL":         &BuiltinNameToken,
	"SERIAL8":        &BuiltinNameToken,
	"SIGNED":         &BuiltinNameToken,
	"SIGNTYPE":       &BuiltinNameToken,
	"SIMPLE_DOUBLE":  &BuiltinNameToken,
	"SIMPLE_FLOAT":   &BuiltinNameToken,
	"SIMPLE_INTEGER": &BuiltinNameToken,
	"SMALLINT":       &BuiltinNameToken,
	"SYS_REFCURSOR":  &BuiltinNameToken,
	"SYSDATE":        &NameToken,
	"TEXT":           &BuiltinNameToken,
	"TINYINT":        &BuiltinNameToken,
	"UNSIGNED":       &BuiltinNameToken,
	"UROWID":         &BuiltinNameToken,
	"UTL_FILE":       &BuiltinNameToken,
	"VARCHAR":        &BuiltinNameToken,
	"VARCHAR2":       &BuiltinNameToken,
	"VARYING":        &BuiltinNameToken,
}

var KEYWORDS_COMMON = map[string]*core.TokenType{
	"SELECT":   &DMLKeywordToken,
	"INSERT":   &DMLKeywordToken,
	"DELETE":   &DMLKeywordToken,
	"UPDATE":   &DMLKeywordToken,
	"UPSERT":   &DMLKeywordToken,
	"REPLACE":  &DMLKeywordToken,
	"MERGE":    &DMLKeywordToken,
	"DROP":     &DDLKeywordToken,
	"CREATE":   &DDLKeywordToken,
	"ALTER":    &DDLKeywordToken,
	"TRUNCATE": &DDLKeywordToken,
	"GRANT":    &DCLKeywordToken,
	"REVOKE":   &DCLKeywordToken,

	"WHERE":         &KeywordToken,
	"FROM":          &KeywordToken,
	"INNER":         &KeywordToken,
	"JOIN":          &KeywordToken,
	"STRAIGHT_JOIN": &KeywordToken,
	"AND":           &KeywordToken,
	"OR":            &KeywordToken,
	"LIKE":          &KeywordToken,
	"ON":            &KeywordToken,
	"IN":            &KeywordToken,
	"SET":           &KeywordToken,

	"BY":    &KeywordToken,
	"GROUP": &KeywordToken,
	"ORDER": &KeywordToken,
	"LEFT":  &KeywordToken,
	"OUTER": &KeywordToken,
	"FULL":  &KeywordToken,

	"IF":    &KeywordToken,
	"END":   &KeywordToken,
	"THEN":  &KeywordToken,
	"LOOP":  &KeywordToken,
	"AS":    &KeywordToken,
	"ELSE":  &KeywordToken,
	"FOR":   &KeywordToken,
	"WHILE": &KeywordToken,

	"CASE":     &KeywordToken,
	"WHEN":     &KeywordToken,
	"MIN":      &KeywordToken,
	"MAX":      &KeywordToken,
	"DISTINCT": &KeywordToken,
}

var KEYWORDS_ORACLE = map[string]*core.TokenType{
	"ARCHIVE":    &KeywordToken,
	"ARCHIVELOG": &KeywordToken,

	"BACKUP": &KeywordToken,
	"BECOME": &KeywordToken,
	"BLOCK":  &KeywordToken,
	"BODY":   &KeywordToken,

	"CANCEL":      &KeywordToken,
	"CHANGE":      &KeywordToken,
	"COMPILE":     &KeywordToken,
	"CONTENTS":    &KeywordToken,
	"CONTROLFILE": &KeywordToken,

	"DATAFILE": &KeywordToken,
	"DBA":      &KeywordToken,
	"DISMOUNT": &KeywordToken,
	"DOUBLE":   &KeywordToken,
	"DUMP":     &KeywordToken,

	"ELSIF":      &KeywordToken,
	"EVENTS":     &KeywordToken,
	"EXCEPTIONS": &KeywordToken,
	"EXPLAIN":    &KeywordToken,
	"EXTENT":     &KeywordToken,
	"EXTERNALLY": &KeywordToken,

	"FLUSH":     &KeywordToken,
	"FREELIST":  &KeywordToken,
	"FREELISTS": &KeywordToken,

	// groups seems too common as table name
	// "GROUPS":&KeywordToken,

	"INDICATOR": &KeywordToken,
	"INITRANS":  &KeywordToken,
	"INSTANCE":  &KeywordToken,

	"LAYER":   &KeywordToken,
	"LINK":    &KeywordToken,
	"LISTS":   &KeywordToken,
	"LOGFILE": &KeywordToken,

	"MANAGE":        &KeywordToken,
	"MANUAL":        &KeywordToken,
	"MAXDATAFILES":  &KeywordToken,
	"MAXINSTANCES":  &KeywordToken,
	"MAXLOGFILES":   &KeywordToken,
	"MAXLOGHISTORY": &KeywordToken,
	"MAXLOGMEMBERS": &KeywordToken,
	"MAXTRANS":      &KeywordToken,
	"MINEXTENTS":    &KeywordToken,
	"MODULE":        &KeywordToken,
	"MOUNT":         &KeywordToken,

	"NOARCHIVELOG": &KeywordToken,
	"NOCACHE":      &KeywordToken,
	"NOCYCLE":      &KeywordToken,
	"NOMAXVALUE":   &KeywordToken,
	"NOMINVALUE":   &KeywordToken,
	"NOORDER":      &KeywordToken,
	"NORESETLOGS":  &KeywordToken,
	"NORMAL":       &KeywordToken,
	"NOSORT":       &KeywordToken,

	"OPTIMAL": &KeywordToken,
	"OWN":     &KeywordToken,

	"PACKAGE":     &KeywordToken,
	"PARALLEL":    &KeywordToken,
	"PCTINCREASE": &KeywordToken,
	"PCTUSED":     &KeywordToken,
	"PLAN":        &KeywordToken,
	"PRIVATE":     &KeywordToken,
	"PROFILE":     &KeywordToken,

	"QUOTA": &KeywordToken,

	"RECOVER":    &KeywordToken,
	"RESETLOGS":  &KeywordToken,
	"RESTRICTED": &KeywordToken,
	"REUSE":      &KeywordToken,
	"ROLES":      &KeywordToken,

	"SAVEPOINT":    &KeywordToken,
	"SCN":          &KeywordToken,
	"SECTION":      &KeywordToken,
	"SEGMENT":      &KeywordToken,
	"SHARED":       &KeywordToken,
	"SNAPSHOT":     &KeywordToken,
	"SORT":         &KeywordToken,
	"STATEMENT_ID": &KeywordToken,
	"STOP":         &KeywordToken,
	"SWITCH":       &KeywordToken,

	"TABLES":      &KeywordToken,
	"TABLESPACE":  &KeywordToken,
	"THREAD":      &KeywordToken,
	"TIME":        &KeywordToken,
	"TRACING":     &KeywordToken,
	"TRANSACTION": &KeywordToken,
	"TRIGGERS":    &KeywordToken,

	"UNLIMITED": &KeywordToken,
	"UNLOCK":    &KeywordToken,
}

// MySQL
var KEYWORDS_MYSQL = map[string]*core.TokenType{
	"ROW": &KeywordToken,
}

// PostgreSQL Syntax
var KEYWORDS_PLPGSQL = map[string]*core.TokenType{
	"CONFLICT":      &KeywordToken,
	"WINDOW":        &KeywordToken,
	"PARTITION":     &KeywordToken,
	"OVER":          &KeywordToken,
	"PERFORM":       &KeywordToken,
	"NOTICE":        &KeywordToken,
	"PLPGSQL":       &KeywordToken,
	"INHERIT":       &KeywordToken,
	"INDEXES":       &KeywordToken,
	"ON_ERROR_STOP": &KeywordToken,
	"EXTENSION":     &KeywordToken,

	"BYTEA":             &KeywordToken,
	"BIGSERIAL":         &KeywordToken,
	"BIT VARYING":       &KeywordToken,
	"BOX":               &KeywordToken,
	"CHARACTER":         &KeywordToken,
	"CHARACTER VARYING": &KeywordToken,
	"CIDR":              &KeywordToken,
	"CIRCLE":            &KeywordToken,
	"DOUBLE PRECISION":  &KeywordToken,
	"INET":              &KeywordToken,
	"JSON":              &KeywordToken,
	"JSONB":             &KeywordToken,
	"LINE":              &KeywordToken,
	"LSEG":              &KeywordToken,
	"MACADDR":           &KeywordToken,
	"MONEY":             &KeywordToken,
	"PATH":              &KeywordToken,
	"PG_LSN":            &KeywordToken,
	"POINT":             &KeywordToken,
	"POLYGON":           &KeywordToken,
	"SMALLSERIAL":       &KeywordToken,
	"TSQUERY":           &KeywordToken,
	"TSVECTOR":          &KeywordToken,
	"TXID_SNAPSHOT":     &KeywordToken,
	"UUID":              &KeywordToken,
	"XML":               &KeywordToken,

	"FOR":  &KeywordToken,
	"IN":   &KeywordToken,
	"LOOP": &KeywordToken,
}

// Hive Syntax
var KEYWORDS_HQL = map[string]*core.TokenType{
	"EXPLODE":    &KeywordToken,
	"DIRECTORY":  &KeywordToken,
	"DISTRIBUTE": &KeywordToken,
	"INCLUDE":    &KeywordToken,
	"LOCATE":     &KeywordToken,
	"OVERWRITE":  &KeywordToken,
	"POSEXPLODE": &KeywordToken,

	"ARRAY_CONTAINS":  &KeywordToken,
	"CMP":             &KeywordToken,
	"COLLECT_LIST":    &KeywordToken,
	"CONCAT":          &KeywordToken,
	"CONDITION":       &KeywordToken,
	"DATE_ADD":        &KeywordToken,
	"DATE_SUB":        &KeywordToken,
	"DECODE":          &KeywordToken,
	"DBMS_OUTPUT":     &KeywordToken,
	"ELEMENTS":        &KeywordToken,
	"EXCHANGE":        &KeywordToken,
	"EXTENDED":        &KeywordToken,
	"FLOOR":           &KeywordToken,
	"FOLLOWING":       &KeywordToken,
	"FROM_UNIXTIME":   &KeywordToken,
	"FTP":             &KeywordToken,
	"HOUR":            &KeywordToken,
	"INLINE":          &KeywordToken,
	"INSTR":           &KeywordToken,
	"LEN":             &KeywordToken,
	"MAP":             &BuiltinNameToken,
	"MAXELEMENT":      &KeywordToken,
	"MAXINDEX":        &KeywordToken,
	"MAX_PART_DATE":   &KeywordToken,
	"MAX_PART_INT":    &KeywordToken,
	"MAX_PART_STRING": &KeywordToken,
	"MINELEMENT":      &KeywordToken,
	"MININDEX":        &KeywordToken,
	"MIN_PART_DATE":   &KeywordToken,
	"MIN_PART_INT":    &KeywordToken,
	"MIN_PART_STRING": &KeywordToken,
	"NOW":             &KeywordToken,
	"NVL":             &KeywordToken,
	"NVL2":            &KeywordToken,
	"PARSE_URL_TUPLE": &KeywordToken,
	"PART_LOC":        &KeywordToken,
	"PART_COUNT":      &KeywordToken,
	"PART_COUNT_BY":   &KeywordToken,
	"PRINT":           &KeywordToken,
	"PUT_LINE":        &KeywordToken,
	"RANGE":           &KeywordToken,
	"REDUCE":          &KeywordToken,
	"REGEXP_REPLACE":  &KeywordToken,
	"RESIGNAL":        &KeywordToken,
	"RTRIM":           &KeywordToken,
	"SIGN":            &KeywordToken,
	"SIGNAL":          &KeywordToken,
	"SIN":             &KeywordToken,
	"SPLIT":           &KeywordToken,
	"SQRT":            &KeywordToken,
	"STACK":           &KeywordToken,
	"STR":             &KeywordToken,
	"STRING":          &BuiltinNameToken,
	"STRUCT":          &BuiltinNameToken,
	"SUBSTR":          &KeywordToken,
	"SUMMARY":         &KeywordToken,
	"TBLPROPERTIES":   &KeywordToken,
	"TIMESTAMP":       &BuiltinNameToken,
	"TIMESTAMP_ISO":   &KeywordToken,
	"TO_CHAR":         &KeywordToken,
	"TO_DATE":         &KeywordToken,
	"TO_TIMESTAMP":    &KeywordToken,
	"TRUNC":           &KeywordToken,
	"UNBOUNDED":       &KeywordToken,
	"UNIQUEJOIN":      &KeywordToken,
	"UNIX_TIMESTAMP":  &KeywordToken,
	"UTC_TIMESTAMP":   &KeywordToken,
	"VIEWS":           &KeywordToken,

	"EXIT":  &KeywordToken,
	"BREAK": &KeywordToken,
	"LEAVE": &KeywordToken,
}

var KEYWORDS_MSACCESS = map[string]*core.TokenType{
	"DISTINCTROW": &KeywordToken,
}

var KEYWORDS_SNOWFLAKE = map[string]*core.TokenType{
	"ACCOUNT":      &KeywordToken,
	"GSCLUSTER":    &KeywordToken,
	"ISSUE":        &KeywordToken,
	"ORGANIZATION": &KeywordToken,
	"PIVOT":        &KeywordToken,
	"QUALIFY":      &KeywordToken,
	"REGEXP":       &KeywordToken,
	"RLIKE":        &KeywordToken,
	"SAMPLE":       &KeywordToken,
	"TRY_CAST":     &KeywordToken,
	"UNPIVOT":      &KeywordToken,

	"VARIANT": &BuiltinNameToken,
}

var KEYWORDS_BIGQUERY = map[string]*core.TokenType{
	"ASSERT_ROWS_MODIFIED": &KeywordToken,
	"DEFINE":               &KeywordToken,
	"ENUM":                 &KeywordToken,
	"HASH":                 &KeywordToken,
	"LOOKUP":               &KeywordToken,
	"PRECEDING":            &KeywordToken,
	"PROTO":                &KeywordToken,
	"RESPECT":              &KeywordToken,
	"TABLESAMPLE":          &KeywordToken,

	"BIGNUMERIC": &BuiltinNameToken,
}
